# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CASE Community
email: casemaster@caseontology.org
description: >- # this means to ignore newlines until "baseurl:"
  Open Source Community for the Cyber-investigation Analysis
  Standard Expression (CASE) Ontology.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.caseontology.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username: casework

# Build settings
markdown: kramdown
highlighter: rouge

# theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# customer excludes
  - .venv.done.log
  - CONTRIBUTE.md
  - Makefile
  - README.md
  - dependencies/
  - examples/*/Makefile
  - examples/*/README.md
  - examples/*/src/*.in
  - examples/*/src/*.json
  - examples/*/src/*.py
  - examples/*/src/Makefile
  - examples/.gitignore
  - examples/Makefile
  - examples/README.md
  - examples/src/*.mk
  - releases/0.2.0/migration/.gitignore
  - releases/0.2.0/migration/Makefile
  - requirements.txt
  - venv/

# Google Analytics
google_analytics: UA-158161373-1
